[workspace]
# members = [
#     "lpx_ctl",
#     "jack_rec",
#     "midi_sample",
#     "peak_volume",
#     "midi_x",
# ]
members = [
    "lpx_ctl",
# ]

# exclude = [
    "jack_rec",
    "midi_sample",
    "nightly/peak_volume",
    "midi_x",
]
resolver = "2"

[dependencies]

# Output a JSON description of created files
chrono = "0.4"
jack = "0.11"
midir = "0.9"
serde = {version = "1.0", features = ["derive"] }
serde_json = "1.0"
symphonia = { version = "0.5", features = ["flac", "wav"]}


[package]
name = "qzn3t"
version = "0.1.0"
authors = ["Worik Stanton <root@worik.org>"]
description = "Music software for Linux, Jackd, and MIDI"
license = "GPL3"

[[bin]]
name = "lpx_ctl"
path = "lpx_ctl/src/main.rs"

[[bin]]
name = "jack_rec"
path = "jack_rec/src/main.rs"

[[bin]]
name = "midi_sample"
path = "midi_sample/src/main.rs"

[[bin]]
name = "peak_volume"
path = "nightly/peak_volume/src/main.rs"

[[bin]]
name = "midi_x"
path = "midi_x/src/main.rs"
