[package]
name = "qzn3t_engine"
version = "0.1.0"
edition = "2024"

[dependencies]
jack = { path = "../../../2026/rust-jack/"}
qzn3terror = {path="../qzn3terror/"}
qzn3t_audio_buffer = {path = "../audio_buffer/"}
serde = "1.0.228"
serde_json = "1.0.149"
symphonia = { version = "0.5", features = ["flac", "wav", "ogg", "pcm"] }
symphonia-core = "0.5.5"
[[bin]]
name = "recorder"
path = "src/bin/recorder.rs"
