use ratatui::style::palette::tailwind;
use ratatui::style::Color;
pub const HEADER_BG: Color = tailwind::BLUE.c950;
pub const NORMAL_ROW_COLOR: Color = tailwind::SLATE.c950;
pub const ALT_ROW_COLOR: Color = tailwind::SLATE.c900;
pub const STATIC_TEXT_FG: Color = tailwind::WHITE;
pub const SELECTED_TEXT_FG: Color = tailwind::RED.c600;
pub const SELECTED_STYLE_FG: Color = tailwind::BLUE.c300;
pub const TEXT_COLOR: Color = tailwind::SLATE.c200;
pub const COMPLETED_TEXT_COLOR: Color = tailwind::GREEN.c500;
pub const PENDING_TEXT_COLOR: Color = tailwind::PURPLE.c500;
