[package]
name = "qznt-record"
version = "0.1.1"
edition = "2024"

[dependencies]
anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
crossterm = "0.29.0"
ctrlc = "3.4"
flac-encoder = "0.1.2"
jack = "0.13.3"
jack_rec = {path = "../jack_rec/"}


[[bin]]
name = "recorder"
path = "src/main.rs"
