[package]
name = "qzn3t-record"
version = "0.1.1"
edition = "2024"

[dependencies]
clap = { version = "4.0", features = ["derive"] }
crossterm = "0.29.0"
ctrlc = "3.4"
jack = "0.13.3"
qzn3t-jack-rec = {path = "../jack_rec/"}

[lib]
name = "qzn3t_recorder"
path = "src/lib.rs"


[[bin]]
name = "recorder"
path = "src/recorder.rs"

