[package]
authors = ["Alessandro Genova <ales.genova@gmail.com>", "<root@worik.org>"]
categories = ["algorithms", "multimedia::audio"]
description = "A collection of algorithms to determine the pitch of a sound sample."
edition = "2021"
exclude=["*.raw"]
homepage = "https://github.com/alesgenova/pitch-detection"
keywords = ["pitch", "frequency", "detection", "sound", "jack"]
license = "GPL-3.0-or-later"
name = "qzn3t-pitch-detection"
readme = "README.md"
repository = "https://github.com/worikgh/qzn3t/tree/mistress/pitch-detection"
version = "0.4.2"

[dependencies]
jack = "0.13.3"
rustfft = { version = "6.0.1", default-features = false }
clap = { version = "4.5.47", features = ["derive"] }

[dev-dependencies]
criterion = "0.3"
hound = { version = "3.4.0" }
float-cmp = "0.9.0"

[[bench]]
name = "utils_benchmark"
harness = false

[[example]]
name = "detect_pitch"
doc = false  # optional

[[example]]
name = "tester"
doc = false  # optional
