[package]
name = "lpx_midi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
midir = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
