#!/usr/bin/perl -w
use strict;

## Executable
my $lpx_midi = "target/release/lpx_midi";
-x $lpx_midi or die $!;
## Set to programmer mode
my @programmer_mode = (240, 0, 32, 41, 2, 12, 14, 1, 247);
my $cmd = "$lpx_midi " . join(' ', @programmer_mode);

# Set some colours
my @colours = (240, 0, 32, 41, 2, 12, 3, 0, 11, 6, 0, 12, 9, 0, 13,15, 0, 14, 5,
	       0, 15, 5, 0, 16, 9, 0, 17, 5, 0, 18,15, 0, 21, 5, 0, 22, 5, 0, 23,
	       5, 0, 24, 9, 0, 25, 6, 0, 26,15, 0, 27, 5, 0, 28, 5, 0, 31, 5, 0,
	       32, 5, 0, 33, 9, 0, 34, 5, 0, 35, 15, 0, 36, 6, 0, 37, 5, 0, 38, 5,
	       0, 41, 9, 0, 42, 5, 0, 43,15, 0, 44, 5, 0, 45, 9, 0, 46, 6, 0, 47,
	       15, 0, 48, 9,
	       0, 51, 29,
	       0, 52, 9,
	       0, 53, 5,
	       0, 54, 4,
	       0, 55, 3,
	       0, 56, 2,
	       0, 57, 1,
	       0, 58, 12,
	       0, 61, 13,
	       0, 62, 39,
	       0, 63, 49,
	       0, 64, 59,
	       0, 65, 3,
	       0, 66, 62,
	       0, 67, 44,
	       0, 68, 10,
	       0, 71, 0,
	       0, 72, 0,
	       0, 73, 12,
	       0, 74, 61,
	       0, 75, 59,
	       0, 76, 33,
	       0, 77, 22,
	       0, 78, 11,
	       0, 81, 0,
	       0, 82, 0,
	       0, 83, 61,
	       0, 84, 12,
	       0, 85, 9,
	       0, 86, 9,
	       0, 87, 9,
	       0, 88, 9,
	       247,);

$cmd = "$lpx_midi " . join(' ', @colours);

sub random_pad {
    my $pad_1 = int(rand() * 8) + 1;
    my $pad_2 = int(rand() * 8) + 1;
    return $pad_1 . $pad_2;
}
sub random_colour {
    return int(rand() * 127) + 1;
}
print `$cmd`;

while(1){
    my $message = "240 0 32 41 2 12 3 0 ".&random_pad .' ' . &random_colour . " 247";
    $cmd = "$lpx_midi $message";
    print `$cmd`;
    sleep(0.1);
}
