[package]
name = "qzn3t_tuner"
version = "0.2.1"
edition = "2024"
description = "A tuner for musical instruments"
license =   "GPL-3.0"
keywords = ["music", "tuner", "qzn3t"]
repository = "https://github.com/worikgh/qzn3t/tree/mistress/tuner"

[dependencies]
clap = {features = ["derive"], version = "4.5.47"}
clap_builder = "4.5.47"
jack = "0.13.3"
pitch-detection = { git = "https://github.com/worikgh/pitch-detection.git", branch = "jack" }
rand = "0.9.2"
ringbuf = "0.4.8"
rtrb = "0.3.2"

[lib]
name = "tuner"
path = "src/lib.rs"

[[bin]]
name = "tuner"
path = "src/main.rs"
