[package]
name = "qzn3t-jack-rec"
version = "0.1.1"
edition = "2024"

[dependencies]
chrono = "0.4"
clap = "4.5.47"
jack = "0.13.4"
mio = { version = "1.0.4", features = ["os-ext"] }

# Output a JSON description of created files
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[lib]
name = "jack_rec"
path = "src/lib.rs"
