name: Build for MacOS

on:
  push:
    branches:
      - mistress
    paths:
      - lpx_ctl/**

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions/setup-rust@v3
        with:
          rust-version: stable

      - name: Build and test
        run: |
          cd lpx_ctl
          cargo build --release

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lpx_ctl-macos
          path: lpx_ctl/target/release/lpx_ctl
          if-no-files-found: error
